### ISSUE TITLE
Variable redefinition in codegen.c

### ISSUE THREAD

**Issue by nikhil-rajesh** [eXpOSNitc/expl#2]
*i* is defined both globally and inside the codegen function. make returns an error because of this in gcc 10.1.0.
![Screenshot_20200710_211255](https://user-images.githubusercontent.com/26025009/87174018-30843180-c2f4-11ea-8f33-5e2474842b3c.png)

**Comment by itsfarseen** [comment]
fixed in https://github.com/eXpOSNitc/expl/commit/5b4b45caa892b7f4a9fa159da76ed1ff17e3cd3b
